# Generated by Django 5.2.4 on 2025-07-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill_required',
            field=models.TextField(blank=True),
        ),
    ]
