# Generated by Django 5.2.4 on 2025-07-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_skill_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
